version: "3.9"

services:
  jukebox:
    environment:
      - PULSE_SERVER=docker.for.mac.localhost
    volumes:
      - ~/.config/pulse:/root/.config/pulse
      - /usr/local/Cellar/pulseaudio/14.2/etc/pulse/:/etc/pulse
  
  mpd:
    environment:
      - PULSE_SERVER=docker.for.mac.localhost
    volumes:
      - ./docker-development/config/docker.mac.mpd.conf:/root/.config/mpd/mpd.conf:rw
      - ~/.config/pulse:/root/.config/pulse
      - /usr/local/Cellar/pulseaudio/14.2/etc/pulse/:/etc/pulse
