version: "3.9"

services:
  jukebox:
    build:
      context: .
      dockerfile: jukebox.Dockerfile
    container_name: jukebox
    devices:
      - /dev/snd
    ports:
      - "8080:80"
    links:
      - mpd
    tty: true
    volumes:
      - ./Phoniebox:/home/pi/RPi-Jukebox-RFID/Phoniebox
      - ./shared:/home/pi/RPi-Jukebox-RFID/shared
  
  webui:
    build:
      context: .
      dockerfile: webui.Dockerfile
    container_name: webui
    ports:
      - "8000:80"
    restart: unless-stopped
    tty: true
    volumes:
      - ./htdocs:/home/pi/RPi-Jukebox-RFID/htdocs
      - ./settings:/home/pi/RPi-Jukebox-RFID/settings
      - ./shared:/home/pi/RPi-Jukebox-RFID/shared

  mpd:
    build:
      context: .
      dockerfile: mpd.Dockerfile
    container_name: mpd
    devices:
      - /dev/snd
    ports:
      - "6600:6600"
      - "8800:8800"
    restart: unless-stopped
    volumes:
      - ./shared/audiofolders:/root/.config/mpd/music:rw
      - ./shared/playlists:/root/.config/mpd/playlists:rw
      - ./docker-development/config/docker.mpd.conf:/root/.config/mpd/mpd.conf:rw
