blank_issues_enabled: true
contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/new?category=q-a
    about: This issue tracker is not for support questions. Please refer to our Discussions.
  - name: 💬 Chat
    url: https://matrix.to/#/#phoniebox_community:gitter.im
    about: Want to discuss with others? Check out our chat.
