name: 🚀 Feature Request v3
description: Use this template to propose feature requests for version 3.
title: "🚀 | "
labels: ["enhancement", "future3"]
body:
  - type: markdown
    attributes:
      value: >
        Please describe your new functionality.

  - type: textarea
    id: feature
    attributes:
      label: Feature
      description:  |
        What functionality would you like to see in your phoniebox?
      placeholder: |
        e.g. `I would love to cook my breakfast eggs with the help of our phoniebox`
    validations:
      required: true

  - type: textarea
    id: perspective
    attributes:
      label: User perspective
      description:  |
        How do you envision the feature to work from a users perspective?
      placeholder: |
        e.g. `In the mornings when I stumble to the bathroom, I want the phoniebox to react on the RFID chip injected under the skin of my right hip. I envision it to walk to the kitchen, get the eggs and a pot out, and start the cooking of the eggs on the stove.`

  - type: textarea
    id: further-info
    attributes:
      label: Further information
      description:  |
        Further information that might help.
      placeholder: |
        e.g. `The stove is operated with cooking gas, so the implemenation has to make sure the stove is handled with the greatest possible care`
