version: "3.9"

services:
  mpd:
    environment:
      - PULSE_SERVER=unix:/tmp/pulse-sock
    volumes:
      - ./config/docker.pulse.mpd.conf:/root/.config/mpd/mpd.conf
      - $XDG_RUNTIME_DIR/pulse/native:/tmp/pulse-sock

  jukebox:
    environment:
      - PULSE_SERVER=unix:/tmp/pulse-sock
    volumes:
      - ./config/docker.pulse.mpd.conf:/root/.config/mpd/mpd.conf
      - $XDG_RUNTIME_DIR/pulse/native:/tmp/pulse-sock
