version: "3.9"

services:
  mpd:
    build:
      args:
        - UID=${UID:-1000}
        - USER=pi
        - HOME=/home/pi
    environment:
      - PULSE_SERVER=unix:/tmp/pulse-sock
    volumes:
      - ../shared/audiofolders:${HOME}/RPi-Jukebox-RFID/shared/audiofolders
      - ../shared/playlists:${HOME}/.config/mpd/playlists
      - ./config/docker.pulse.mpd.conf:${HOME}/.config/mpd/mpd.conf
      - $XDG_RUNTIME_DIR/pulse/native:/tmp/pulse-sock

  jukebox:
    build:
      args:
        - UID=${UID:-1000}
        - USER=pi
        - HOME=/home/pi
    environment:
      - PULSE_SERVER=unix:/tmp/pulse-sock
    volumes:
      - ../shared:${HOME}/RPi-Jukebox-RFID/shared
      - ./config/docker.pulse.mpd.conf:${HOME}/.config/mpd/mpd.conf
      - $XDG_RUNTIME_DIR/pulse/native:/tmp/pulse-sock
