services:
  mpd:
    volumes:
      - ~/.config/pulse:/root/.config/pulse

  spotify:
    volumes:
      - ~/.config/pulse:/home/spotify/.config/pulse

  jukebox:
    volumes:
      - ~/.config/pulse:/root/.config/pulse
