name: Build Web App
description: 'Build Web App with Node'
inputs:
  webapp-root-path:
    description: 'root path of the Web App sources'
    required: false
    default: './src/webapp'
outputs:
  webapp-root-path:
    description: 'used root path of the Web App sources'
    value: ${{ inputs.webapp-root-path }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js 22.x
      uses: actions/setup-node@v7
      with:
        node-version: 22.x
        cache: npm
        cache-dependency-path: ${{ inputs.webapp-root-path }}/package-lock.json
    - name: Install dependencies
      working-directory: ${{ inputs.webapp-root-path }}
      shell: bash
      run: npm ci
    - name: Build Web App
      working-directory: ${{ inputs.webapp-root-path }}
      shell: bash
      run: npm run build
