name: Build Web App
description: 'Build Web App with Node'
inputs:
  webapp-root-path:
    description: 'root path of the Web App sources'
    required: false
    default: './src/webapp'
outputs:
  webapp-root-path:
    description: 'used root path of the Web App sources'
    value: ${{ inputs.webapp-root-path }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: run build
      working-directory: ${{ inputs.webapp-root-path }}
      shell: bash
      env:
        CI: false
      run: ./run_rebuild.sh -u