FROM --platform=linux/arm/v7 arm32v7/debian:bullseye-slim as base

# Define constants
ENV DOCKER_RUNNING=true DEBIAN_FRONTEND=noninteractive
RUN touch /boot/cmdlinetxt

# Install packages
RUN apt-get update && \
  apt-get -y install \
    apt-utils \
    curl \
    gnupg

RUN echo 'deb http://raspbian.raspberrypi.org/raspbian/ bullseye main contrib non-free rpi' > /etc/apt/sources.list.d/raspi.list ;\
  echo 'deb http://archive.raspberrypi.org/debian/ bullseye main' >> /etc/apt/sources.list.d/raspi.list ;\
  curl http://raspbian.raspberrypi.org/raspbian.public.key | apt-key add - ;\
  curl http://archive.raspberrypi.org/debian/raspberrypi.gpg.key | apt-key add - ;\
  apt-get update && \
  apt-get -y install \
    build-essential \
    git \
    iw \
    locales \
    # install here to speed up GitHub Action
    raspberrypi-kernel-headers \
    sudo \
    systemd \
    wget \
    wpasupplicant ;\
    rm -rf /var/lib/apt/lists/*


FROM base as user
# Define user info
ARG USER_NAME=pi
ARG USER_GROUP=$USER_NAME
# Define Git Repo variables for installationscript.
ARG GIT_BRANCH
ARG GIT_URL

ENV USER=$USER_NAME

RUN groupadd --gid 1000 $USER_GROUP && \
  useradd -u 1000 -g 1000 -G sudo -d /home/$USER -m -s /bin/bash -p '$1$iV7TOwOe$6ojkJQXyEA9bHd/SqNLNj0' $USER && \
  echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER

USER $USER

# Define needed files for installation test
COPY --chown=$USER:$USER_GROUP --chmod=750 scripts/installscripts/tests/*.sh /tests/
COPY --chown=$USER:$USER_GROUP --chmod=750 scripts/installscripts/buster-install-default.sh /

ENV GIT_BRANCH=$GIT_BRANCH GIT_URL=$GIT_URL

WORKDIR /tests
