# Target to build and install all needed base configuration and packages
ARG DEBIAN_VERSION_NAME=bullseye
ARG BASE_TEST_IMAGE=test
FROM debian:${DEBIAN_VERSION_NAME}-slim as base
ARG DEBIAN_VERSION_NAME

ENV DOCKER_RUNNING=true
RUN touch /boot/cmdlinetxt

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get -y install \
    apt-utils \
    curl \
    gnupg \
  && curl -fsSL http://raspbian.raspberrypi.org/raspbian.public.key | gpg --dearmor > /usr/share/keyrings/raspberrypi-raspbian-keyring.gpg \
  && curl -fsSL http://archive.raspberrypi.org/debian/raspberrypi.gpg.key | gpg --dearmor > /usr/share/keyrings/raspberrypi-archive-debian-keyring.gpg \
  && echo "deb [signed-by=/usr/share/keyrings/raspberrypi-raspbian-keyring.gpg] http://raspbian.raspberrypi.org/raspbian/ ${DEBIAN_VERSION_NAME} main contrib non-free rpi" > /etc/apt/sources.list.d/raspi.list \
  && echo "deb [signed-by=/usr/share/keyrings/raspberrypi-archive-debian-keyring.gpg] http://archive.raspberrypi.org/debian/ ${DEBIAN_VERSION_NAME} main" >> /etc/apt/sources.list.d/raspi.list \
  && apt-get update \
  && apt-get -y upgrade \
  && apt-get -y install \
    build-essential \
    git \
    iw \
    locales \
    sudo \
    systemd \
    wget \
    wpasupplicant \
    # install internally used packages here to speed up GitHub Action
    raspberrypi-kernel \
    raspberrypi-kernel-headers \
  && rm -rf /var/lib/apt/lists/*
# ------


# Target for setting up user for test. user can be selected with the docker '--user $USERNAME' option
FROM base as user
ENV TEST_USER_GROUP=test

RUN groupadd --gid 1002 $TEST_USER_GROUP

RUN export USER_PI=pi \
  && export USER_PI_GROUP=$USER_PI \
  && groupadd --gid 1000 $USER_PI_GROUP \
  && useradd -u 1000 -g $USER_PI_GROUP -G sudo,$TEST_USER_GROUP -d /home/$USER_PI -m -s /bin/bash -p '$1$iV7TOwOe$6ojkJQXyEA9bHd/SqNLNj0' $USER_PI \
  && echo "$USER_PI ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER_PI

RUN export USER_ALT=hans \
  && export USER_ALT_GROUP=wurst \
  && groupadd --gid 1001 $USER_ALT_GROUP \
  && useradd -u 1001 -g $USER_ALT_GROUP -G sudo,$TEST_USER_GROUP -d /home/$USER_ALT -m -s /bin/bash -p '$1$iV7TOwOe$6ojkJQXyEA9bHd/SqNLNj0' $USER_ALT \
  && echo "$USER_ALT ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER_ALT
# ------


# Target for adding envs and scripts from the repo to test installation
FROM user as test
ARG GIT_BRANCH
ARG GIT_URL

ENV GIT_BRANCH=$GIT_BRANCH GIT_URL=$GIT_URL

COPY --chown=root:$TEST_USER_GROUP --chmod=770 scripts/installscripts/buster-install-default.sh .
WORKDIR /tests
COPY --chown=root:$TEST_USER_GROUP --chmod=770 scripts/installscripts/tests/*.sh .
# ------


# Target for applying latest updates (should not be cached!)
FROM $BASE_TEST_IMAGE as test-update
RUN apt-get update \
  && apt-get -y upgrade \
  && rm -rf /var/lib/apt/lists/*
# ------
