FROM --platform=linux/arm/v7 arm32v7/debian:buster-slim
ARG USER_NAME=pi
ARG USER_GROUP=$USER_NAME
ARG GIT_BRANCH
ARG GIT_URL

ENV DOCKER_RUNNING=true
ENV USER=$USER_NAME
ENV GIT_BRANCH=$GIT_BRANCH
ENV GIT_URL=$GIT_URL

COPY . /code
WORKDIR /code

RUN groupadd --gid 1000 $USER_GROUP ;\
  useradd -u 1000 -g 1000 -G sudo -d /home/$USER -m -s /bin/bash -p '$1$iV7TOwOe$6ojkJQXyEA9bHd/SqNLNj0' $USER ;\
  chown -R 1000:1000 /code /home/$USER ;\
  chmod +x /code/scripts/installscripts/buster-install-default.sh ;\
  chmod +x /code/scripts/installscripts/tests/run_installation_tests.sh ;\
  chmod +x /code/scripts/installscripts/tests/run_installation_tests2.sh ;\
  chmod +x /code/scripts/installscripts/tests/run_installation_tests3.sh

RUN export DEBIAN_FRONTEND=noninteractive ;\
  apt-get update ;\
  apt-get -y install curl gnupg sudo nano systemd apt-utils;\
  # install here to speed up GitHub Action
  apt-get -y install raspberrypi-kernel-headers;\
  echo 'deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi' > /etc/apt/sources.list.d/raspi.list ;\
  echo 'deb http://archive.raspberrypi.org/debian/ buster main' >> /etc/apt/sources.list.d/raspi.list ;\
  curl http://raspbian.raspberrypi.org/raspbian.public.key | apt-key add - ;\
  curl http://archive.raspberrypi.org/debian/raspberrypi.gpg.key | apt-key add - ;\
  echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER ;\
  apt-get clean ;\
  rm -rf /var/cache/apt/* /var/lib/apt/lists/*

RUN export DEBIAN_FRONTEND=noninteractive ;\
  apt-get update ;\
  apt-get -y dist-upgrade --auto-remove --purge ;\
  apt-get -y install wget build-essential git iw locales wpasupplicant;\
  apt-get clean ;\
  touch /boot/cmdlinetxt ;\
  rm -rf /var/cache/apt/* /var/lib/apt/lists/*

USER $USER
