#!/usr/bin/env bash

ENABLE_STATIC_IP=true
DISABLE_IPv6=true
DISABLE_BLUETOOTH=true
DISABLE_SSH_QOS=true
DISABLE_BOOT_SCREEN=true
DISABLE_BOOT_LOGS_PRINT=true
MPD_USE_DEFAULT_CONF_DIR=true
MPD_CONFIG=true
UPDATE_RASPI_OS=false
ENABLE_SAMBA=true
ENABLE_WEBAPP=true
ENABLE_KIOSK_MODE=false
