#!/usr/bin/env bash

BUILD_LIBZMQ_WITH_DRAFTS_ON_DEVICE=false
ENABLE_STATIC_IP=true
DISABLE_IPv6=true
ENABLE_AUTOHOTSPOT=false
AUTOHOTSPOT_CHANGE_PASSWORD=false
AUTOHOTSPOT_PASSWORD="PlayItLoud!"
DISABLE_BLUETOOTH=true
DISABLE_SSH_QOS=true
DISABLE_BOOT_SCREEN=true
DISABLE_BOOT_LOGS_PRINT=true
SETUP_MPD=true
UPDATE_RASPI_OS=false
ENABLE_SAMBA=true
ENABLE_WEBAPP=true
ENABLE_WEBAPP_PROD_BUILD=true
ENABLE_KIOSK_MODE=false
