#!/usr/bin/env bash

IS_PRODUCTION=true
ENABLE_STATIC_IP=true
DISABLE_IPv6=true
DISABLE_BLUETOOTH=true
DISABLE_SSH_QOS=true
DISABLE_BOOT_SCREEN=true
DISABLE_BOOT_LOGS_PRINT=true
SETUP_MPD=true
UPDATE_RASPI_OS=false
ENABLE_SAMBA=true
ENABLE_WEBAPP=true
ENABLE_KIOSK_MODE=false
