name: Build Docs and Open PR
on:
  push:
    branches:
        - 'future3/**'
    paths:
        - '**.py'
  pull_request:
    branches:
        - 'future3/**'
    paths:
        - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Python Docs
      uses: s-martin/markdown-docs@master
      with:
        src_path: src
        dst_path: documentation/developers/
    - name: Open docs update PR
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}           
