name: Markdown Linting

on:
  push:
    branches:
        - 'future3/**'
    paths:
        - '**.md'
  pull_request:
    branches:
        - 'future3/**'
    paths:
        - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: DavidAnson/markdownlint-cli2-action@v15
      with:
        globs: '**/*.md'
      continue-on-error: true
