name: Markdown Linting

on:
  push:
    branches-ignore:
        - 'future3/**'
    paths:
        - '**.md'
  pull_request:
    branches:
        - develop
        - master
    paths:
        - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Linting markdown
      uses: DavidAnson/markdownlint-cli2-action@v16
      with:
        config: .markdownlint-cli2.yaml
      #continue-on-error: true
