name: Python Checks and Tests

on:
  push:
    branches-ignore:
        - 'future3/**'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install spidev
        pip install -r requirements.txt
        pip install -r requirements-GPIO.txt
        pip install -r components/rfid-reader/PN532/requirements.txt
    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --config .flake8
    - name: Test with pytest
      run: |
        pytest --cov --cov-config=.coveragerc --cov-report xml
    - name: Report to Coveralls (parallel)
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: coverage.xml
        format: cobertura
        parallel: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          #carryforward: "run-1,run-2"
