name: Test build Webapp v3

on:
  schedule:
    # run at 18:00 every sunday
    - cron: '0 18 * * 0'
  push:
    branches:
        - 'future3/**'
    paths:
        - '.github/workflows/test_build_webapp_v3.yml'
        - '.github/actions/build_webapp_action.yml'
        - 'src/webapp/**'
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
        - future3/develop
        - future3/main
    paths:
        - '.github/workflows/test_build_webapp_v3.yml'
        - '.github/actions/build_webapp_action.yml'
        - 'src/webapp/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build WebApp
        uses: .github/actions/build_webapp_action.yml