name: Test Install Scripts Debian v3

on:
  schedule:
    # run at 17:00 every sunday
    - cron: '0 17 * * 0'
  push:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ future3/develop ]

# let only one instance run the test so cache is not corrupted.
# cancel already running instances as only the last run will be relevant
concurrency:
    group: ${{ github.ref }}-test-debian-v3
    cancel-in-progress: true

jobs:

  # Build container and run tests. Duplication of job intended for better visualization.
  run_bookworm:
    name: 'bookworm'
    uses: ./.github/workflows/test_docker_debian_codename_sub_v3.yml
    with:
      debian_codename: 'bookworm'

  run_bullseye:
    name: 'bullseye'
    uses: ./.github/workflows/test_docker_debian_codename_sub_v3.yml
    with:
      debian_codename: 'bullseye'
